### ISSUE TITLE
Create a working about page

### ISSUE THREAD

**Issue by pruthvi2103** [TEDxJNEC/tedx-2021#22]
- [x] Page should contain the  `content.jsx` component
- [x] Make `content.jsx` Reusable (Make it so that it can render contents with props supplied to it
- [x] Make a `about-content.json` in `assets folder`
- [x] Import `about-content.json` in `about.jsx` and supply prop to `<Content />`
- [x] Test with array data

* Test Data to get you started
```
[
{
"title":"About TEDx JNEC",
"content":"Lorem Ipsum....",
"youtubelink":"https://www.youtube.com/watch?v=A9Lhhsd9EB8&ab_channel=TEDxTalks"
}
]
```

**Comment by ayushnayyar** [comment]
Added Content Component to About Page and added some global CSS classes

- Added about-content.json to assets directory
- Made the Content component reusable, by accepting props (Content.jsx)
- Added Content Component to About Page and supplied relevant pro (about.jsx)
-Added few CSS classes for global styles in main.scss
