### ISSUE TITLE
Create a proper form component

### ISSUE THREAD

**Issue by pruthvi2103** [TEDxJNEC/tedx-2021#40]
Usecases:

Attendee registration form

Ambassador registration form

Surveys

Ticket transaction form

Use a library called `formik`

*Required Features*

- [ ] Auto-Saving
- [ ] validation
- [ ] chained validation
- [ ] api based validation
- [ ] key shortcut
- [ ] excellent UX

**Comment by sohamtamboli** [comment]
ok sir

**Comment by sohamtamboli** [comment]
What should be the initial fields for the form?
